- name: Build docker image
  hosts: all
  become: yes
  tasks:
  - name: Update packets
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3000
  - name: Install Docker
    apt:
      name: docker.io
      state: present
  - name: Copy bash script
    copy:
      src: ./init.sh
      dest: /home/ubuntu/init.sh
      owner: "ubuntu"
      group: "ubuntu"
      mode: "0766"
  - name: Run bash script
    shell: /home/ubuntu/init.sh "{{login}}" "{{psw}}"